apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: developer
      type: HTPasswd
      mappingMethod: claim
      htpasswd:
        fileData:
          name: htpass-secret
    - name: keycloak
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: pecan
        clientSecret:
          name: keycloak-openshift-client-secret
        ca:
          # Create with this command: 
          # oc -n openshift-config create configmap keycloak-ca-config-map --from-literal="ca.crt=$(oc -n keycloak get secret/keycloak-certificate -o jsonpath='{.data.ca\.crt}' | base64 -d)"
          name: keycloak-ca-config-map
        claims: 
          preferredUsername:
            - preferred_username
            - username
          name:
            - name
            - full name
          email:
            - email
          groups:
            - groups
        issuer: https://keycloak.apps-crc.testing/realms/PEcAn
