apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- randomsecrets/
- secretstores/
- secretenginemounts/
- externalsecrets/
- certificates/
- keycloaks/
- keycloakrealmimports/
- oauths/
