apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  path: keycloak/kv
  secretKey: ADMIN_PASSWORD
  secretFormat:
    passwordPolicyName: special-characters-password-policy-15
